# Generated by Django 4.2.5 on 2024-09-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_level',
            field=models.DecimalField(decimal_places=2, default=7.78, max_digits=5),
            preserve_default=False,
        ),
    ]
