# Generated by Django 4.2.5 on 2024-10-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_friendship_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(condition=models.Q(('user__lt', models.F('friend'))), fields=('user', 'friend'), name='unique_friendship'),
        ),
    ]
