# Generated by Django 4.2.5 on 2024-10-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_friendship_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
