# Generated by Django 4.2.5 on 2024-10-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_users_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_grade',
            field=models.CharField(default='Fifth wheel', max_length=25),
        ),
        migrations.AddField(
            model_name='users',
            name='user_imagejson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_location',
            field=models.CharField(default='Earth', max_length=25),
        ),
        migrations.AddField(
            model_name='users',
            name='user_phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_skillsjson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_wallet',
            field=models.IntegerField(default=0),
        ),
    ]
