# Generated by Django 4.2.5 on 2024-10-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='two_fa_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
