version: '3.8'

services:
  user_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: user_db
    networks:
      - app-network
    volumes:
      - user_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # PostgreSQL Database Service
  game_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: game_db
    volumes:
      - game_db:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  user_service:
    build: ./user_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./user_service:/app2
    ports:
      - "8001:8000"
    depends_on:
      user_db:
        condition: service_healthy
    networks:
      - app-network
    environment:
      DATABASE_URL: postgres://postgres_user:postgres_password@user_db:5432/user_db
    entrypoint: /app2/entrypoint.sh  # This will trigger the entrypoint script
    
  # Django (Backend) Service
  game_service:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      game_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@game_db:5432/game_db
    entrypoint: /app/entrypoint.sh  # This will trigger the entrypoint script

  # Nginx Service (Merged with Frontend)
  nginx:
    build:
      context: .  # Make sure this context is set correctly where your nginx.conf is located
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - game_service
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Ensure the correct config is mounted
      - ./backend/staticfiles:/usr/share/nginx/html/staticfiles

volumes:
  user_db_data:
  game_db:

networks:
  app-network:
    driver: bridge
